name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    uses: etsvThor/github-actions/.github/workflows/laravel-tests.yml@master
    with:
      php-version: 8.3
      php-extensions: "[ 'imagick', 'gd' ]"
      generate-key: false
      test-command: "./vendor/bin/phpunit"
  static-analysis:
    uses: etsvThor/github-actions/.github/workflows/laravel-static-analysis.yml@master
    with:
      php-version: 8.3
      php-extensions: "[ 'imagick', 'gd' ]"
  code-style:
    uses: etsvThor/github-actions/.github/workflows/laravel-code-style.yml@master
    with:
      php-version: 8.3
      php-extensions: "[ 'imagick', 'gd' ]"
      analysis-command: './vendor/bin/php-cs-fixer fix src --dry-run --diff'
